#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         5
bspc config window_gap           8

b
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#484848"
bspc config focused_border_color "#1F8999"

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#AutoStart apps
sxhkd &
dunst &
picom --config ~/.config/picom/picom.conf &
nitrogen --restore &
polybar &
