#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 

bspc config border_width         4
bspc config window_gap           17
bspc config split_ratio          0.52
bspc config gapless_monocle      false

# borders
bspc config normal_border_color "#484848"
bspc config focused_border_color "#1F8999"
# bspc config focused_border_color  "#e095f7"
# bspc config borderless_monocle true

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#windows rules
# bspc rule -a kitty state=floating
bspc rule -a Eog state=floating
bspc rule -a Qalculate-gtk state=floating
bspc rule -a Spotify state=floating

# Set cursor to default
xsetroot -cursor_name left_ptr

# Start autostart applications
start_apps() {
    sxhkd &
    dunst &
    picom --config ~/.config/picom/picom.conf &
    nitrogen --restore &
    polybar &
    ~/scripts/touchpad.sh
    ~/scripts/battery-alert.sh &
}

start_apps

